package ma.formations.multiconnector.enums;

public enum Permissions {
    GET_ALL_CUSTOMERS,
    GET_CUSTOMER_BY_IDENTITY,
    GET_CUSTOMER_BANK_ACCOUNTS,
    CREATE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    GET_ALL_BANK_ACCOUNT,
    GET_BANK_ACCOUNT_BY_RIB,
    CREATE_BANK_ACCOUNT,
    DELETE_BANK_ACCOUNT,
    ADD_WIRED_TRANSFER,
    GET_TRANSACTIONS
}